name: "Go proxy warming"

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "**/v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
      - name: Pull new module version
        uses: piLinux/go-proxy-pull-action@master
        with:
          set_github_repository: pilinux/gorest
